import { createSignal } from 'solid-js';
import  "../Css/AboutTerms.css";

const AboutTerms = () => {
  const [content, setContent] = createSignal('about');

  const switchContent = (type) => {
    setContent(type);
  };

  return (
    <div class="about-terms-container">
      <div class="tabs">
        <button onClick={() => switchContent('about')}>About Us</button>
        <button onClick={() => switchContent('terms')}>Terms of Service</button>
      </div>
      <div class="content">
        {content() === 'about' && (
          <div>
            <h2>About Us</h2>
            <p>Take a look under the hood of Kenya’s largest and safest car-sharing marketplace. At Abiri we're committed to making transportation more accessible and equitable for everyone. We believe in providing a safe, convenient, and affordable solution to people who need to get around. Our mission is to create a community of trust and convenience by offering the best car-sharing experience in Kenya.</p>
            <p>Founded in 2023, Abiri has grown rapidly to become the go-to platform for car-sharing in Kenya. Our team is dedicated to making every ride a pleasant experience for both drivers and passengers. We work tirelessly to ensure our platform is user-friendly, secure, and reliable. Our goal is to empower individuals and communities by providing an alternative mode of transportation that is not only efficient but also environmentally friendly.</p>
          </div>
        )}
        {content() === 'terms' && (
          <div>
            <h2>Terms of Service</h2>
            <p>The services that Abiri Africa LTD provides to User are subject to the following Terms of Use ("TOU"). Abiri Africa LTD reserves the right to update the TOU at any time without notice to User. The most current version of the TOU can be reviewed by clicking on the "Terms of Service" hypertext link located at the bottom of our Web pages.</p>
            <h3>A. This Agreement</h3>
            <p>The following terms and conditions govern all use of the Abiri Africa LTD website and all content, services, and products available at or through the website (taken together, the Website). The Website is owned and operated by Abiri Africa LTD ("Abiri Africa LTD"). The Website is offered subject to your acceptance without modification of all of the terms and conditions contained herein and all other operating rules, policies (including, without limitation, Abiri Africa LTD's Privacy Policy), and procedures that may be published from time to time on this Site by Abiri Africa LTD (collectively, the "Agreement").</p>
            <p>Please read this Agreement carefully before accessing or using the Website. By accessing or using any part of the Website, you agree to become bound by the terms and conditions of this agreement. If you do not agree to all the terms and conditions of this agreement, then you may not access the Website or use any services. If these terms and conditions are considered an offer by Abiri Africa LTD, acceptance is expressly limited to these terms. The Website is available only to individuals who are at least 13 years old.</p>
            <h3>B. Your Abiri Africa LTD Account and Site</h3>
            <p>If you create a blog/site on the Website, you are responsible for maintaining the security of your account and blog, and you are fully responsible for all activities that occur under the account and any other actions taken in connection with the blog. You must not describe or assign keywords to your blog in a misleading or unlawful manner, including in a manner intended to trade on the name or reputation of others, and Abiri Africa LTD may change or remove any description or keyword that it considers inappropriate or unlawful, or otherwise likely to cause Abiri Africa LTD liability. You must immediately notify Abiri Africa LTD of any unauthorized uses of your blog, your account, or any other breaches of security. Abiri Africa LTD will not be liable for any acts or omissions by You, including any damages of any kind incurred as a result of such acts or omissions.</p>
            <h3>C. Responsibility of Contributors</h3>
            <p>If you operate a blog, comment on a blog, post material to the Website, post links on the Website, or otherwise make (or allow any third party to make) material available by means of the Website (any such material, "Content"), You are entirely responsible for the content of, and any harm resulting from, that Content. That is the case regardless of whether the Content in question constitutes text, graphics, an audio file, or computer software. By making Content available, you represent and warrant that:</p>
            <ul>
              <li>the downloading, copying, and use of the Content will not infringe the proprietary rights, including but not limited to the copyright, patent, trademark, or trade secret rights, of any third party;</li>
              <li>if your employer has rights to intellectual property you create, you have either (i) received permission from your employer to post or make available the Content, including but not limited to any software, or (ii) secured from your employer a waiver as to all rights in or to the Content;</li>
              <li>you have fully complied with any third-party licenses relating to the Content, and have done all things necessary to successfully pass through to end users any required terms;</li>
              <li>the Content does not contain or install any viruses, worms, malware, Trojan horses, or other harmful or destructive content;</li>
              <li>the Content is not spam, is not machine- or randomly-generated, and does not contain unethical or unwanted commercial content designed to drive traffic to third-party sites or boost the search engine rankings of third-party sites, or to further unlawful acts (such as phishing) or mislead recipients as to the source of the material (such as spoofing);</li>
              <li>the Content is not pornographic, does not contain threats or incite violence, and does not violate the privacy or publicity rights of any third party;</li>
              <li>your blog is not getting advertised via unwanted electronic messages such as spam links on newsgroups, email lists, other blogs and web sites, and similar unsolicited promotional methods;</li>
              <li>your blog is not named in a manner that misleads your readers into thinking that you are another person or company. For example, your blog's URL or name is not the name of a person other than yourself or company other than your own; and</li>
              <li>you have, in the case of Content that includes computer code, accurately categorized and/or described the type, nature, uses, and effects of the materials, whether requested to do so by Abiri Africa LTD or otherwise.</li>
            </ul>
            <p>By submitting Content to Abiri Africa LTD for inclusion on your Website, you grant Abiri Africa LTD a world-wide, royalty-free, and non-exclusive license to reproduce, modify, adapt and publish the Content solely for the purpose of displaying, distributing, and promoting your blog. If you delete Content, Abiri Africa LTD will use reasonable efforts to remove it from the Website, but you acknowledge that caching or references to the Content may not be made immediately unavailable.</p>
            <p>Without limiting any of those representations or warranties, Abiri Africa LTD has the right (though not the obligation) to, in Abiri Africa LTD's sole discretion (i) refuse or remove any content that, in Abiri Africa LTD's reasonable opinion, violates any Abiri Africa LTD policy or is in any way harmful or objectionable, or (ii) terminate or deny access to and use of the Website to any individual or entity for any reason, in Abiri Africa LTD's sole discretion. Abiri Africa LTD will have no obligation to provide a refund of any amounts previously paid.</p>
            <h3>D. Payment and Renewal</h3>
            <p>General Terms.</p>
            <p>By selecting a product or service, you agree to pay Abiri Africa LTD the one-time and/or monthly or annual subscription fees indicated (additional payment terms may be included in other communications). Subscription payments will be charged on a pre-pay basis on the day you sign up for an upgrade and will cover the use of that service for a monthly or annual subscription period as indicated. Payments are not refundable.</p>
            <p>Automatic Renewal.</p>
            <p>Unless you notify Abiri Africa LTD before the end of the applicable subscription period that you want to cancel a subscription, your subscription will automatically renew and you authorize us to collect the then-applicable annual or monthly subscription fee for such subscription (as well as any taxes) using any credit card or other payment mechanism we have on record for you. Upgrades can be canceled at any time by submitting your request to Abiri Africa LTD in writing.</p>
            <h3>E. Services</h3>
            <p>Fees; Payment. By signing up for a Services account you agree to pay Abiri Africa LTD the applicable setup fees and recurring fees. Applicable fees will be invoiced starting from the day your services are established and in advance of using such services. Abiri Africa LTD reserves the right to change the payment terms and fees upon thirty (30) days prior written notice to you. Services can be canceled by you at any time on thirty (30) days written notice to Abiri Africa LTD.</p>
            <p>Support. If your service includes access to priority email support. "Email support" means the ability to make requests for technical support assistance by email at any time (with reasonable efforts by Abiri Africa LTD to respond within one business day) concerning the use of the VIP Services. "Priority" means that support takes priority over support for users of the standard or free abiri-africa.com services. All support will be provided in accordance with Abiri Africa LTD standard services practices, procedures, and policies.</p>
            <h3>F. Responsibility of Website Visitors</h3>
            <p>Abiri Africa LTD has not reviewed, and cannot review, all of the material, including computer software, posted to the Website, and cannot therefore be responsible for that material's content, use or effects. By operating the Website, Abiri Africa LTD does not represent or imply that it endorses the material there posted, or that it believes such material to be accurate, useful or non-harmful. You are responsible for taking precautions as necessary to protect yourself and your computer systems from viruses, worms, Trojan horses, and other harmful or destructive content. The Website may contain content that is offensive, indecent, or otherwise objectionable, as well as content containing technical inaccuracies, typographical mistakes, and other errors. The Website may also contain material that violates the privacy or publicity rights, or infringes the intellectual property and other proprietary rights, of third parties, or the downloading, copying or use of which is subject to additional terms and conditions, stated or unstated. Abiri Africa LTD disclaims any responsibility for any harm resulting from the use by visitors of the Website, or from any downloading by those visitors of content there posted.</p>
            <h3>G. Content Posted on Other Websites</h3>
            <p>We have not reviewed, and cannot review, all of the material, including computer software, made available through the websites and webpages to which abiri-africa.com links, and that link to abiri-africa.com. Abiri Africa LTD does not have any control over those non-Abiri Africa LTD websites and webpages and is not responsible for their contents or their use. By linking to a non-Abiri Africa LTD website or webpage, Abiri Africa LTD does not represent or imply that it endorses such website or webpage. You are responsible for taking precautions as necessary to protect yourself and your computer systems from viruses, worms, Trojan horses, and other harmful or destructive content. Abiri Africa LTD disclaims any responsibility for any harm resulting from your use of non-Abiri Africa LTD websites and webpages.</p>
            <h3>H. Copyright Infringement and DMCA Policy</h3>
            <p>As Abiri Africa LTD asks others to respect its intellectual property rights, it respects the intellectual property rights of others. If you believe that material located on or linked to by abiri-africa.com violates your copyright, you are encouraged to notify Abiri Africa LTD in accordance with Abiri Africa LTD's Digital Millennium Copyright Act ("DMCA") Policy. Abiri Africa LTD will respond to all such notices, including as required or appropriate by removing the infringing material or disabling all links to the infringing material. Abiri Africa LTD will terminate a visitor's access to and use of the Website if, under appropriate circumstances, the visitor is determined to be a repeat infringer of the copyrights or other intellectual property rights of Abiri Africa LTD or others. In the case of such termination, Abiri Africa LTD will have no obligation to provide a refund of any amounts previously paid to Abiri Africa LTD.</p>
            <h3>I. Intellectual Property</h3>
            <p>This Agreement does not transfer from Abiri Africa LTD to you any Abiri Africa LTD or third party intellectual property, and all right, title, and interest in and to such property will remain (as between the parties) solely with Abiri Africa LTD. Abiri Africa LTD, abiri-africa.com, the abiri-africa.com logo, and all other trademarks, service marks, graphics, and logos used in connection with abiri-africa.com, or the Website are trademarks or registered trademarks of Abiri Africa LTD or Abiri Africa LTD's licensors. Other trademarks, service marks, graphics, and logos used in connection with the Website may be the trademarks of other third parties. Your use of the Website grants you no right or license to reproduce or otherwise use any Abiri Africa LTD or third-party trademarks.</p>
            <h3>J. Advertisements</h3>
            <p>Abiri Africa LTD reserves the right to display advertisements on your blog unless you have purchased an ad-free account.</p>
            <h3>K. Attribution</h3>
            <p>Abiri Africa LTD reserves the right to display attribution links such as 'Blog at abiri-africa.com,' theme author, and font attribution in your blog footer or toolbar.</p>
            <h3>L. Partner Products</h3>
            <p>By activating a partner product (e.g. theme) from one of our partners, you agree to that partner's terms of service. You can opt-out of their terms of service at any time by deactivating the partner product.</p>
            <h3>M. Domain Names</h3>
            <p>If you are registering a domain name, using or transferring a previously registered domain name, you acknowledge and agree that the use of the domain name is also subject to the policies of the Internet Corporation for Assigned Names and Numbers ("ICANN"), including their Registration Rights and Responsibilities.</p>
            <h3>N. Changes</h3>
            <p>Abiri Africa LTD reserves the right, at its sole discretion, to modify or replace any part of this Agreement. It is your responsibility to check this Agreement periodically for changes. Your continued use of or access to the Website following the posting of any changes to this Agreement constitutes acceptance of those changes. Abiri Africa LTD may also, in the future, offer new services and/or features through the Website (including the release of new tools and resources). Such new features and/or services shall be subject to the terms and conditions of this Agreement.</p>
            <h3>O. Termination</h3>
            <p>Abiri Africa LTD may terminate your access to all or any part of the Website at any time, with or without cause, with or without notice, effective immediately. If you wish to terminate this Agreement or your abiri-africa.com account (if you have one), you may simply discontinue using the Website. Notwithstanding the foregoing, if you have a paid services account, such account can only be terminated by Abiri Africa LTD if you materially breach this Agreement and fail to cure such breach within thirty (30) days from Abiri Africa LTD's notice to you thereof; provided that, Abiri Africa LTD can terminate the Website immediately as part of a general shut down of our service. All provisions of this Agreement which by their nature should survive termination shall survive termination, including, without limitation, ownership provisions, warranty disclaimers, indemnity, and limitations of liability.</p>
            <h3>P. Disclaimer of Warranties</h3>
            <p>The Website is provided "as is". Abiri Africa LTD and its suppliers and licensors hereby disclaim all warranties of any kind, express or implied, including, without limitation, the warranties of merchantability, fitness for a particular purpose, and non-infringement. Neither Abiri Africa LTD nor its suppliers and licensors make any warranty that the Website will be error-free or that access thereto will be continuous or uninterrupted. You understand that you download from, or otherwise obtain content or services through, the Website at your own discretion and risk.</p>
            <h3>Q. Limitation of Liability</h3>
            <p>In no event will Abiri Africa LTD, or its suppliers or licensors, be liable with respect to any subject matter of this Agreement under any contract, negligence, strict liability or other legal or equitable theory for: (i) any special, incidental or consequential damages; (ii) the cost of procurement for substitute products or services; (iii) for interruption of use or loss or corruption of data; or (iv) for any amounts that exceed the fees paid by you to Abiri Africa LTD under this agreement during the twelve (12) month period prior to the cause of action. Abiri Africa LTD shall have no liability for any failure or delay due to matters beyond their reasonable control. The foregoing shall not apply to the extent prohibited by applicable law.</p>
            <h3>R. General Representation and Warranty</h3>
            <p>You represent and warrant that (i) your use of the Website will be in strict accordance with the Abiri Africa LTD Privacy Policy, with this Agreement and with all applicable laws and regulations (including without limitation any local laws or regulations in your country, state, city, or other governmental area, regarding online conduct and acceptable content, and including all applicable laws regarding the transmission of technical data exported from the United States or the country in which you reside) and (ii) your use of the Website will not infringe or misappropriate the intellectual property rights of any third party.</p>
            <h3>S. Indemnification</h3>
            <p>You agree to indemnify and hold harmless Abiri Africa LTD, its contractors, and its licensors, and their respective directors, officers, employees, and agents from and against any and all claims and expenses, including attorneys' fees, arising out of your use of the Website, including but not limited to your violation of this Agreement.</p>
            <h3>T. Miscellaneous</h3>
            <p>This Agreement constitutes the entire agreement between Abiri Africa LTD and you concerning the subject matter hereof, and they may only be modified by a written amendment signed by an authorized executive of Abiri Africa LTD, or by the posting by Abiri Africa LTD of a revised version. Except to the extent applicable law, if any, provides otherwise, this Agreement, any access to or use of the Website will be governed by the laws of the Nairobi County, Kenya, excluding its conflict of law provisions, and the proper venue for any disputes arising out of or relating to any of the same will be the state and federal courts located in Nairobi County, Kenya. Except for claims for injunctive or equitable relief or claims regarding intellectual property rights (which may be brought in any competent court without the posting of a bond), any dispute arising under this Agreement shall be finally settled in accordance with the Comprehensive Arbitration Rules of the Judicial Arbitration and Mediation Service, Inc. ("JAMS") by three arbitrators appointed in accordance with such Rules. The arbitration shall take place in Nairobi County, Kenya, in the English language and the arbitral decision may be enforced in any court. The prevailing party in any action or proceeding to enforce this Agreement shall be entitled to costs and attorneys' fees. If any part of this Agreement is held invalid or unenforceable, that part will be construed to reflect the parties' original intent, and the remaining portions will remain in full force and effect. A waiver by either party of any term or condition of this Agreement or any breach thereof, in any one instance, will not waive such term or condition or any subsequent breach thereof. You may assign your rights under this Agreement to any party that consents to, and agrees to be bound by, its terms and conditions; Abiri Africa LTD may assign its rights under this Agreement without condition. This Agreement will be binding upon and will inure to the benefit of the parties, their successors, and permitted assigns.</p>
            <p>This document is an adaptation of the WordPress.com Terms of Service. The original work has been modified with permission from Automattic, Inc. and is available under a Creative Commons Sharealike license. This means you're welcome to copy and adapt it for your own use. Just make sure to replace references to us with ones to you, and don't forget to change the language so it reflects your own situation accurately. You can find the original version of the WordPress.com Terms of Service at https://en.wordpress.com/tos/.</p>
          </div>
        )}
      </div>
    </div>
  );
};

export default AboutTerms;
